### PR TITLE
Make bazel use jenkins $workspace for all caching

### PR DESCRIPTION
**Pull request by cs-xm**
Bazel caches any remote cache locally and by default uses the users home directory for this, as well as a few other bits. This means that the jenkins node never cleans up this local cache and eventually the builders disk gets full. This solution copies the remote cache to the jenkins workspace and then jenkins cleans up after itself at the end, as part of the normal workspace clean up.
See:
https://github.com/bazelbuild/bazel/issues/4248

### CODE REVIEW

**Comment by cs-xm** [comment]
I checked the $WORKSPACE/.bazel directory when this built and we used about 5.3G:
image

**Comment by BrennanGit** [comment]
Looks good to me. Builds each only took 10 minutes so they are clearly still hitting the remote cache.

**Review by BrennanGit — APPROVED** [review]

**Comment by ghost** [comment]
+1 Thank you @cs-xm!

**Review by ghost — APPROVED** [review]
+1

**Pull request merged**
