### PR TITLE
Add mobilenetv2 example

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by michaelpoluektov** [comment]
There are already sample COCO images in ``xformer/model_maker/train_samples/``, maybe we should re-use those?

**Comment by ghost** [comment]
> There are already sample COCO images in `xformer/model_maker/train_samples/`

Yeah, these are the same ones. I copied them to make it a self-contained example. The model_maker folder is something we can get move elsewhere. Made that for quickly quantizing various flavours of mobilenet.
Do you think we should refactor?

**Comment by michaelpoluektov** [comment]
``model_maker`` contains a ``save_model.py`` script and the samples. ``obtain_and_optimize_mobilenetv2`` contains a copy of ``save_model.py``. Maybe we could factor out the function to obtain a quantized version of mobilenet out of  ``obtain_and_optimize_mobilenetv2`` into something like ``get_mobilenet.py``, then delete ``model_maker`` altogether since all of it's functionality would be part of the mobilenetv2 example?

Also perhaps the ``input_array`` should be stored as a ``.npy`` file or pickle? Even better, we could load one of the sample images directly, although that would probably require importing Pillow

**Review by michaelpoluektov — APPROVED** [review]
Tested, works.

**Pull request merged**
