### PR TITLE
Add buildDiscarder and timestamp option to Jenkins

### PR DESCRIPTION
**Pull request by BrennanGit**
This PR introduces a method for automatically deleting Jenkins builds after a certain time/number. This is needed so that Jenkins disk does not forever grow.

Please understand that **THIS IS A DESTRUCTIVE CHANGE** and once merged to develop will permanently delete old builds so please come forward with any concerns over the settings chosen if you have any.

We will use the [buildDiscarder Jenkinsfile option](https://stackoverflow.com/questions/39542485/how-to-write-pipeline-to-discard-old-builds/44155346#44155346) to configure this on a repo-by-repo basis.

This process has been tested using [this repo](https://github.com/xmos/jenkins_test) and [this jenkins job](http://srv-bri-jcim0:8080/job/XMOS/job/jenkins_test/).

------------------------

[Here is a link to the confluence page](https://xmosjira.atlassian.net/wiki/spaces/wiki/pages/3396534277/Build+Discarding) going into more detail about justification and usage.

The short version is we propose to delete any build older than 100 on the develop branch of this repo.

Please comment if you think this is unsuitable.

### CODE REVIEW

**Comment by BrennanGit** [comment]
Note: this will keep builds after around 281 from 28/10/21

**Review by andrewstanfordjason — APPROVED** [review]
I don't know what this is but looks like, if the branch is develop them keep 100 of them else none.

**Comment by ghost** [comment]
100 seems reasonable

**Review by ghost — APPROVED** [review]

**Comment by BrennanGit** [comment]
> keep 100 of them else none.

More like if develop keep 100, else keep all of them. In this case an empty string prompts the default which is all.

**Pull request merged**
