### PR TITLE
add some dual output models

### PR DESCRIPTION
**Pull request by aranXmos**

### CODE REVIEW

**Comment by ghost** [comment]
Brilliant! Thank you @aranXmos!

**Review by ghost — APPROVED** [review]
+1

**Comment by aranXmos** [comment]
@panickal-xmos seems I didn't merge this PR when you approved it, and now added another fix to it. Can you review again and ill merge them both together?
New commit fixes issue with logistic.

**Review by ghost — APPROVED** [review]
+1

**Pull request merged**
