### PR TITLE
Add bazel remote cache to Jenkinsfile

### PR DESCRIPTION
**Pull request by BrennanGit**
Adding requested remote cache to CI.
Do not merge until I ask for review.

### CODE REVIEW

**Comment by BrennanGit** [comment]
Ok I think this is almost good to go.
Once this run passes: https://github.com/BrennanGit/ai_tools-1/actions/runs/3387485836
Then I can check that it's created the files in the bucket. 
I've been running a test repo/job to check basic syntax: https://github.com/BrennanGit/bazel_actions_test/actions/runs/3387463259
image

Note I had to force the platform "arm64" on the mac because the mac it's being run on is actually an x64 machine.

**Comment by BrennanGit** [comment]
confirmed that we're creating correct folders with my fork
image

**Review by ghost — APPROVED** [review]
+1

**Comment by ghost** [comment]
Thank you @BrennanGit ! :)

**Pull request merged**
